### ISSUE TITLE
Warning and segmentation fault on Ubuntu 18.04

### ISSUE THREAD

**Issue by ppigazzini** [lucasart/c-chess-cli#6]
https://github.com/lucasart/c-chess-cli/commit/cf0da2b36098690f6ce11e6e4f466635ece4da8e

* Ubuntu 18.04
```
vmuser@u1804:~/c-chess-cli$ make
gcc  -std=gnu99 -mpopcnt -O3 -flto -Wfatal-errors -Wall -Wextra -Wshadow -DNDEBUG ./*.c -o c-chess-cli -lpthread -s
./main.c: In function ‘thread_start’:
./engine.c:120:64: warning: ‘e.out’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (fputs(buf, e->out) >= 0 && fputs("\n", e->out) >= 0 && fflush(e->out) == 0) {
                                                                ^
./engine.c:64:12: note: ‘e.out’ was declared here
     Engine e;
            ^
./engine.c:111:9: warning: ‘e.in’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (str_getline(line, e->in)) {
         ^
./engine.c:64:12: note: ‘e.in’ was declared here
     Engine e;
            ^
vmuser@u1804:~/c-chess-cli$ ./c-chess-cli
could not execute engine ''
Segmentation fault (core dumped)
```

* msys2 (Windows)
```
$ make
gcc  -std=gnu99 -mpopcnt -O3 -flto -Wfatal-errors -Wall -Wextra -Wshadow -DNDEBUG ./*.c -o c-chess-cli -lpthread -s
In file included from ./position.c:15:
./position.c: In function ‘pos_set’:
./position.c:271:40: warning: array subscript has type ‘char’ [-Wchar-subscripts]
  271 |             const bool color = islower(*c);
      |                                        ^~
./position.c:294:28: warning: array subscript has type ‘char’ [-Wchar-subscripts]
  294 |             rank = isupper(*c) ? RANK_1 : RANK_8;
      |                            ^~

$ ./c-chess-cli.exe
could not execute engine ''
engine_readln() failed reading from '▒'
```

* mingw-w64 (Windows)
```
$ make
gcc  -std=gnu99 -mpopcnt -O3 -flto -Wfatal-errors -Wall -Wextra -Wshadow -DNDEBUG ./*.c -o c-chess-cli -lpthread -s
In file included from ./engine.c:21:
./engine.h:35:51: error: unknown type name 'int64_t'; did you mean 'ino_t'?
   35 | bool engine_bestmove(const Engine *e, int *score, int64_t *timeLeft, str_t *best);
      |                                                   ^~~~~~~
      |                                                   ino_t
compilation terminated due to -Wfatal-errors.
In file included from ./main.c:17:
./engine.h:35:51: error: unknown type name 'int64_t'
   35 | bool engine_bestmove(const Engine *e, int *score, int64_t *timeLeft, str_t *best);
      |                                                   ^~~~~~~
compilation terminated due to -Wfatal-errors.
./str.c: In function 'str_getline':
./str.c:316:5: warning: implicit declaration of function 'flockfile'; did you mean '_lock_file'? [-Wimplicit-function-declaration]
  316 |     flockfile(in);
      |     ^~~~~~~~~
      |     _lock_file
./str.c:319:13: warning: implicit declaration of function 'getc_unlocked' [-Wimplicit-function-declaration]
  319 |         c = getc_unlocked(in);
      |             ^~~~~~~~~~~~~
./str.c:327:5: warning: implicit declaration of function 'funlockfile'; did you mean '_unlock_file'? [-Wimplicit-function-declaration]
  327 |     funlockfile(in);
      |     ^~~~~~~~~~~
      |     _unlock_file
make: *** [makefile:22: default] Error 1
```

**Comment by lucasart** [comment]
I think I fixed the trivial stuff.

The non trivial part, is the lack of POSIX compliance on mingw-w64. I'm not sure I want to go down the rabbit hole of writing Windows specific code. Especially because I will write it blindfolded w/o a Windows machine to test.

**Comment by ppigazzini** [comment]
@lucasart Ubuntu and msys2 fixed, `c-chess-cli` tested working

For mingw-w64 you could cross compile, this works on a clean Ubuntu 18.04 install:
```
#!/bin/bash

# update and installa packages
sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean
sudo apt install -y make mingw-w64 wine64 binutils git wget unzip

# build stockfish
git clone --single-branch --branch master https://github.com/official-stockfish/Stockfish.git
cd Stockfish/src
make -j build ARCH=x86-64$1 COMP=mingw
strip stockfish.exe
mv stockfish.exe ../../stockfish.exe
make clean
cd
# build c-chess-cli
git clone --single-branch --branch master https://github.com/lucasart/c-chess-cli.git
cd c-chess-cli
make CC=x86_64-w64-mingw32-gcc-posix

# download a book
wget https://github.com/official-stockfish/books/raw/master/noob_3moves.epd.zip
unzip noob_3moves.epd.zip
rm noob_3moves.epd.zip

# play a match
wine ./c-chess-cli.exe -cmd ../stockfish.exe:./stockfish.exe-options Hash=8,Threads=2:Threads=1 -games 8 -concurrency 4 -openings noob_3moves.epd -repeat -movetime 0.15 -depth 10 -resign 3,700 -draw 8,10 -pgnout out.pgn
```

The mingw-w64 error message is the same on Ubuntu/Windows:

* mingw-w64 Ubuntu
```
$ make CC=x86_64-w64-mingw32-gcc-posix
x86_64-w64-mingw32-gcc-posix -std=gnu99 -mpopcnt -O3 -flto -Wfatal-errors -Wall -Wextra -Wshadow -Wstrict-prototypes -DNDEBUG ./*.c -o c-chess-cli -lpthread -s
./engine.c: In function ‘engine_spawn’:
./engine.c:30:9: warning: implicit declaration of function ‘pipe’; did you mean ‘_pipe’? [-Wimplicit-function-declaration]
     if (pipe(outof) < 0 || pipe(into) < 0)
         ^~~~
         _pipe
./engine.c:34:14: warning: implicit declaration of function ‘fork’ [-Wimplicit-function-declaration]
     e->pid = fork();
              ^~~~
./engine.c: In function ‘engine_delete’:
./engine.c:106:9: warning: implicit declaration of function ‘kill’; did you mean ‘tell’? [-Wimplicit-function-declaration]
     if (kill(e->pid, SIGTERM) < 0)
         ^~~~
         tell
./str.c: In function ‘str_getline’:
./str.c:316:5: warning: implicit declaration of function ‘flockfile’; did you mean ‘_lock_file’? [-Wimplicit-function-declaration]
     flockfile(in);
     ^~~~~~~~~
     _lock_file
./str.c:319:13: warning: implicit declaration of function ‘getc_unlocked’; did you mean ‘_getc_nolock’? [-Wimplicit-function-declaration]
         c = getc_unlocked(in);
             ^~~~~~~~~~~~~
             _getc_nolock
./str.c:327:5: warning: implicit declaration of function ‘funlockfile’; did you mean ‘_unlock_file’? [-Wimplicit-function-declaration]
     funlockfile(in);
     ^~~~~~~~~~~
     _unlock_file
/tmp/cclqqezx.o:engine.c:(.text+0x76): undefined reference to `pipe'
/tmp/cclqqezx.o:engine.c:(.text+0x86): undefined reference to `pipe'
/tmp/cclqqezx.o:engine.c:(.text+0xab): undefined reference to `fork'
/tmp/cclqqezx.o:engine.c:(.text+0x5fe): undefined reference to `kill'
/tmp/ccMOMGtv.o:str.c:(.text+0xaf4): undefined reference to `flockfile'
/tmp/ccMOMGtv.o:str.c:(.text+0xb14): undefined reference to `getc_unlocked'
/tmp/ccMOMGtv.o:str.c:(.text+0xb27): undefined reference to `funlockfile'
collect2: error: ld returned 1 exit status
makefile:23: recipe for target 'default' failed
make: *** [default] Error 1
```
* mingw-w64 windows
```
$ make CC=gcc
gcc -std=gnu99 -mpopcnt -O3 -flto -Wfatal-errors -Wall -Wextra -Wshadow -DNDEBUG ./*.c -o c-chess-cli -lpthread -s
./engine.c: In function 'engine_spawn':
./engine.c:30:9: warning: implicit declaration of function 'pipe'; did you mean '_pipe'? [-Wimplicit-function-declaration]
   30 |     if (pipe(outof) < 0 || pipe(into) < 0)
      |         ^~~~
      |         _pipe
./engine.c:34:14: warning: implicit declaration of function 'fork' [-Wimplicit-function-declaration]
   34 |     e->pid = fork();
      |              ^~~~
./engine.c: In function 'engine_delete':
./engine.c:106:9: warning: implicit declaration of function 'kill' [-Wimplicit-function-declaration]
  106 |     if (kill(e->pid, SIGTERM) < 0)
      |         ^~~~
./str.c: In function 'str_getline':
./str.c:316:5: warning: implicit declaration of function 'flockfile'; did you mean '_lock_file'? [-Wimplicit-function-declaration]
  316 |     flockfile(in);
      |     ^~~~~~~~~
      |     _lock_file
./str.c:319:13: warning: implicit declaration of function 'getc_unlocked' [-Wimplicit-function-declaration]
  319 |         c = getc_unlocked(in);
      |             ^~~~~~~~~~~~~
./str.c:327:5: warning: implicit declaration of function 'funlockfile'; did you mean '_unlock_file'? [-Wimplicit-function-declaration]
  327 |     funlockfile(in);
      |     ^~~~~~~~~~~
      |     _unlock_file
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\c-chess-cli.exe.5BWAck.ltrans0.ltrans.o:<artificial>:(.text+0x2445): undefined reference to `flockfile'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\c-chess-cli.exe.5BWAck.ltrans0.ltrans.o:<artificial>:(.text+0x245f): undefined reference to `getc_unlocked'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\c-chess-cli.exe.5BWAck.ltrans0.ltrans.o:<artificial>:(.text+0x2477): undefined reference to `funlockfile'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\c-chess-cli.exe.5BWAck.ltrans0.ltrans.o:<artificial>:(.text+0x27da): undefined reference to `pipe'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\c-chess-cli.exe.5BWAck.ltrans0.ltrans.o:<artificial>:(.text+0x27f2): undefined reference to `pipe'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\c-chess-cli.exe.5BWAck.ltrans0.ltrans.o:<artificial>:(.text+0x280b): undefined reference to `fork'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\c-chess-cli.exe.5BWAck.ltrans0.ltrans.o:<artificial>:(.text+0x4ffb): undefined reference to `kill'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\c-chess-cli.exe.5BWAck.ltrans0.ltrans.o:<artificial>:(.text+0x503e): undefined reference to `kill'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:22: default] Error 1
```

**Comment by ppigazzini** [comment]
@lucasart by the way you could setup GitHub Actions, here the script for cutechess:
https://github.com/cutechess/cutechess/blob/master/.github/workflows/build.yml

**Comment by lucasart** [comment]
closing, as the windows compatibility part is a known limitation, and redundant with another issue. don't understand the github action part.
